#!/usr/bin/python

import sys, string

if len(sys.argv) != 3:
	print "\nUssage: ./xor2 infile outfile"
	print "This will enumerate from 0x00 to 0xFF"
	print "For hexadecimal keys, use $'\\x01'\n"
	exit()

g = open(str(sys.argv[2]), "a")

for leKey in xrange(0,256):

	f = open(str(sys.argv[1]), "rb")
	k = ord(chr(leKey))
	byte = f.read(1)
	
	try: 
		printMessage = "\n\nUsing key: " + str(leKey) + "\n"
		g.write(printMessage)
		g.write("Decoded Message: ")

		while byte != "":
			xbyte = ord(byte) ^ k	
			g.write(chr(xbyte))
			byte = f.read(1)
			print "Text deciphered " + str(byte) + " " + str(xbyte)

	finally:
		f.close()

f.close()
g.close()
